org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.useFullClasspathForDexingTransform=true

# Resolve JdkImageTransform error on Windows with SDK 34
android.experimental.enableJdkImageTransform=false
android.nonTransitiveRClass=true
